#
# Circle CI configuration. Runs each time we push a new commit to Github.
#
# This file is derived from the project's Dockerfile, which we use for
# local testing.
#
version: 2.1
jobs:
  build:
    docker:
      - image: ocaml/opam2:debian-stable
    working_directory: ~/ocaml-tree-sitter
    steps:
      - checkout
      - run:
          name: set up node
          command: ./scripts/setup-node
      - run:
          name: set up opam
          command: ./scripts/setup-opam
      - run:
          name: configure
          command: ./configure
      - run:
          name: install dependencies
          command: opam exec -- make setup
      - run:
          name: build
          command: opam exec -- make
      - run:
          name: install
          command: opam exec -- make install
      - run:
          name: test
          command: opam exec -- make test
